### ISSUE TITLE
No connection possible with Blogger?

### ISSUE THREAD

**Issue by mswcap** [OpenLiveWriter/OpenLiveWriter#63]
Hi all.

First of all compliments for this effort. Totally awesome! However, I can't connect to my blog (http://thoughtsonopsmgr.blogspot.com/). During setup I am asked to enter the address of my blog, username and account. Every time the installer returns with the message 'The user name or password is incorrect. Please try again.'

Already I've set my Google account to allow apps with lower security. With Windows Live Writer this works. 

Or will OWL only work when it supports OAuth 2, as stated on the blog of Scott Hanselman?

With kind regards,
Marnix Wolf
![01 - owl blogger settings](https://cloud.githubusercontent.com/assets/16236919/11710013/65d92b5c-9f1c-11e5-8dc5-aee001b96e79.png)

![02 - owl error message](https://cloud.githubusercontent.com/assets/16236919/11709962/08b2dc7a-9f1c-11e5-8916-4ceab5b81f1b.png)
![03 - google allow less secure apps](https://cloud.githubusercontent.com/assets/16236919/11709963/08b5199a-9f1c-11e5-8bec-7df3037244f9.png)

**Comment by JetzeMellema** [comment]
I gave the same issue with http://jetzemellema.blogspot.com.

**Comment by geeksrik** [comment]
may i know whether anyone is addressing this as a super high priority? i think this tool is straightaway not usable by so many thousands of people just due to this issue.

**Comment by martinwoodward** [comment]
There are some people working on this (mentioned on #5), we where trying to get it in for yesterdays initial release but where not feeling good about it.

@willduff, @wasker, @RobDolin, @SiTox, @Eilon - would it be possible to get a WIP PR raised with the Blogger work to-date so that people can take a look and help get it over the line?  Alternatively we can create a new branch here.

Keeping this issue open for now. It will be fixed at the same time as #5 but good to have this one here for other people that are having trouble logging in.  Also got some nice screenshots that show the problem.

**Comment by StephenCWLL** [comment]
New to blogging and using blogger. Got really excited when I heard about OLW, but alas I was too quick and tried to use it before I read up about it and saw about the authentication issue. Got excited when I learnt I could use Word, but that's got same issue :) hoping you guys can fix this issue with OLW soon.

**Comment by evil-shrike** [comment]
I was so excited about OLW as I hoped it starts working with Blogger again. As Windows Live Writer doesn't work anymore. From May as I remember. But no luck:
The user name or password is incorrect.

I have custom domain, 2factor auth and using an app password (created on https://security.google.com/settings/security/apppasswords).

**Comment by FixarFarsan** [comment]
This is the second time Windows Live Writer suddenly stops working, then I download the OLW and it can't login to my Blogger blog either... WTH!!

**Comment by ALCvA** [comment]
I'm unable to login to my Blogger account with both Windows Live Writer and OLW. I reinstalled both applications with no joy. Thousands must be affected by this, and this is not the first time. How to proceed?

**Comment by ibonobo** [comment]
I have always been able to use WLW to post to Blogger (more specifically, currently using WLW 2012 in Portable mode). However, today when I tried I could not (not found:not found). My guess is that Blogger/Google has pulled the plug on the old authentication method. I understand OLW will support the new one. This is probably beyond my humble skillset, but I nonetheless started playing with the code.

**Comment by timheuer** [comment]
We should close this to #5 and not keep it open.  The closed issues still reference the others.

**Comment by martinwoodward** [comment]
@timheuer - yeah. Reason for keeping this open was that the closed issues are harder for people to find and we where getting dupes. Hopefully won't have to leave this open for long before we get it fixed.

**Comment by FixarFarsan** [comment]
Any planned update on OWL in scope with Blogger connectivity? I can beta-test! :)

**Comment by farsideoffifty** [comment]
Open Writer does not work, is someone working on this problem?  I have the same problem as mwscap.

**Comment by anserq** [comment]
I am having the same problem.

**Comment by StephenCWLL** [comment]
@farsideoffifty @anserq @FixarFarsan yes, they are working on it :) It says so on this thread and the links of the other threads where they discuss the authentication issue :) These things take time though.

**Comment by anserq** [comment]
Okay thanks StephenCWLL

**Comment by SteveP-UK** [comment]
Same problem here too.

**Comment by Virtual-Nihilist-Blog** [comment]
Ditto.  Same error attempting to authenticate to my Blogger site:

![image](https://cloud.githubusercontent.com/assets/16249774/11759581/49bc18be-a04b-11e5-9945-7b769645ecc1.png)

**Comment by ALCvA** [comment]
Both OLW and Windows Live Writer fail to connect to blogger. There is much pointless time wasting information circulating to address this problem—much goes back several years. The problem is not new. However, all of it is useless or ineffective. That's my experience.

**Comment by RobDolin** [comment]
Thanks for reporting.  Google recently deprecated an API that both Windows Live Writer and Open Live Writer were dependent on.  The Open Live Writer volunteer team is working on a fix.  (Issue #5 I think) and hoping to release soon.
________________________________

**Comment by ericasisme** [comment]
I am also getting the error and commented on Issue #5 
Environment: Windows 10

Steps to reproduce:
1. Download and install OLW
2. Connect to your blogger blog
3. OLW not able to automatically detect settings
3a. Select 'Blogger'
3b. Remote pasting field is auto-populated (I do not know if this is correct, it says 
http://www.blogger.com/feeds/default/blogs
4. Get user name / password incorrect Error

**Comment by jes2015** [comment]
Just to say I have the same problem both Livewritr and OLW are failing to access blogger blog, both failing to recognise a perfectly good account/password. Hoping for a fix soon I can send install log if you tell me how and where to send if that will help

**Comment by comstech23** [comment]
Same problem here. Thanks for all the hard work. I can't wait to start using this :)

**Comment by gfmucci** [comment]
I am wondering why Windows Live Writer could not have remained intact to allow glitch-free use of it until Open Live Writer was ready for prime time.  Just wondering what the thinking was and why we have ended up with neither program functiioning with Blogger/Blogspot compatibility.

**Comment by timheuer** [comment]
@gfmucci It was a change to Blogger that affects all apps not using their new authentication methods. So having WLW intact wasn't even controllable. A Google service has changed and the team is moving as fast as it can to validate the fix for the OLW community. Thanks for your patience.

**Comment by geeksrik** [comment]
Tim is there even an approximate timeline that you see this support being made available? Like is one month from now a safe assumption?

**Comment by timheuer** [comment]
@geeksrik literally being worked on and reviewed past few days. Been a top priority for the volunteers. You can track pull request #101 which has the work

**Comment by The-Andy** [comment]
I hope this gets resolved soon... I'm really surprised it made it to the release phase with this problem.

**Comment by sheng-wang-i** [comment]
Really rely on Windows live writer for a long time. For this issue, w both giants, google and microsoft, decide to do nothing. We can only rely on you guys now.

**Comment by Shoshiplatypus** [comment]
Replying to Martinwoodward on #5 (now closed) - thank you Martin - I look forward to news on this with eager anticipation! Getting fairly desperate now, to put it mildly... Thanks for all the hard work you folks are doing on our behalf.

Shoshi

**Comment by jdubyaeber** [comment]
20151214  yesterday, WLW stopped working with Blogger.  I assume it is the same issue as in May.  However, it has been working just fine for the last 6 months or so.  To make you feel better, scribefire in FF is having the same problem.  OLW fix is coming, I understand that.  The copy I downloaded the other day did not work.  :(
Adding my two cents and will find a way to get the email notifications - Thank you in advance for getting this fixed for OLW.
-John

**Comment by ScottIsAFool** [comment]
@jdubyaeber to subscribe to our mailing list, go to http://openlivewriter.org and there's a link to subscribing in the Get Connected section.

**Comment by drhamptn** [comment]
Thanks for everything the volunteers are doing to resolve this!

**Comment by 1093brown** [comment]
Looking forward to being able to update blogs with OLW. JUst disappointed that the plug was pulled by Google before OLW was fully functional & therefore leaving 1000's of Blogger / LiveWriter users frustrated once again. Really looking forward to using OLW and having a program that will be updated.

**Comment by farsideoffifty** [comment]
When it is fixed will it work with Windows 7 ??   Thanks for working on this problem, are there any updates?

**Comment by crpaiva** [comment]
Dear Friends. Any news about it? Google said the OWL team was acting in the solution and that soon we would have news.

**Comment by ScottIsAFool** [comment]
@crpaiva getting close. If you haven't already done so, subscribe to our email mailing list and you'll hear straight away when it's released.

**Comment by Tritaya** [comment]
Hi guys! How to subscribe to updates for this issue?

**Comment by ScottIsAFool** [comment]
At the top of this page, there's a subscribe button for notifications. However, you might be better subscribing to our mailing list (details on openlivewriter.org)

**Comment by willduff** [comment]
Good news everyone, I just finished coding initial support for Google Blogger in Open Live Writer. I have a 'nightly' build for those that are willing to try out pre-release software. Please let me know if you see any issues, other than the known ones below.

Known issues:
  * You need to remove your old Google Blogger accounts from Open Live Writer first. After removing them, click the 'Add blog account...' button in Open Live Writer to set up your Google Blogger accounts.
  * Scheduling a published post may be a few hours off.
  * Categories are no longer supported in the latest Blogger API v3.
  * Support for authors, tags and comment policies is not enabled yet.
  * Attempting to login to Google Blogger with 0 blogs will show an error message. Please create a blog on http://www.blogger.com first before using Open Live Writer.

The download link is: https://olw.blob.core.windows.net/nightly/Releases/OpenLiveWriterSetup.exe

/cc
@ALCvA, @Virtual-Nihilist-Blog, @SteveP-UK, @anserq, @StephenCWLL, @farsideoffifty, @FixarFarsan, @ibonobo, @evil-shrike, @JetzeMellema, @mswcap, @Tritaya, @crpaiva, @1093brown, @drhamptn, @jdubyaeber, @Shoshiplatypus, @sheng-wang-i, @The-Andy, @geeksrik, @gfmucci, @comstech23, @jes2015, @ericasisme

**Comment by crpaiva** [comment]
With this new version, I could go a little further. I can reach the window where you choose the service provider. But soon after I get the error user and password. Photo attached screen. My installation of OLW is zero without any prior information blog accounts.
![olw](https://cloud.githubusercontent.com/assets/16322079/11850950/633759aa-a417-11e5-9dc6-304e63a5ef37.jpg)

**Comment by ScottIsAFool** [comment]
@crpaiva Hmm, did you not see a Google Blogger option on the first page (where it has wordpress and other blog types)?

**Comment by SteveP-UK** [comment]
Hi Will

Just tested your nightly build! :)

Initial Feedback - :)

When adding each of  my two blogger accounts, a blank web page was
displayed once I'd given Blogger permission to access the blog and photos.
Here is the url
http://localhost:61590/authorize/?code=4/5eN1G0CZitKVw5SkLB-icDVCY_U_kC-Kn4SZKuCQr_0#

Apart from that all went smoothly and the two accounts were added. My first
blog using OLW is at

http://blog.stevepalmer.com/2015/12/test-olw-nightly-build-001.html

So, I'd say it all went pretty smoothly apart from the blank web page issue
(which was only a temporary thing!). Missing the 'categories' option though!

Happy to test further.




Regards

Steve
www.StevePalmer.com
blog.StevePalmer.com
@TweetsBySteveP
Mobile: 07860 639 661
:::::::::::::::::::::::::::::::::::::::::::::::::::

**Comment by SteveP-UK** [comment]
Hi Will

Just tested your nightly build! :)

Initial Feedback - :)

When adding each of  my two blogger accounts, a blank web page was displayed once I'd given Blogger permission to access the blog and photos. Here is the url
http://localhost:61590/authorize/?code=4/5eN1G0CZitKVw5SkLB-icDVCY_U_kC-Kn4SZKuCQr_0#

Apart from that all went smoothly and the two accounts were added. My first blog using OLW is at
http://blog.stevepalmer.com/2015/12/test-olw-nightly-build-001.html

So, I'd say it all went pretty smoothly apart from the blank web page issue (which was only a temporary thing!). Missing the 'categories' option though!

Happy to test further.

**Comment by farsideoffifty** [comment]
Yes I just tested it also.  I was able to add all four of my blogs successfully.  Thank you!  I published to one blog and the first attempt came back bad gateway, but on the second attempt it published just fine.  The time stamp is way off by about plus 6 hours, but I fixed that by going to blogger and my posts.  I miss categories too.  But I would say it is a great beginning! Thank you! :)

**Comment by Shoshiplatypus** [comment]
It sounds as if you are doing a great job! Thank you so much for all your hard work on our behalf. I am going to hang on for a bit longer before trying it. I hope you can get categories to work, and comments too. Is there anything special we have to do to connect our blogger/google account to OLW, like having an application password, or allowing less safe applications, or using Google's 2-step log-in? If we've got these things, do we have to remove them, or do anything different?

Thanks again, and I'm watching for news daily! Great stuff.

Shoshi

**Comment by crpaiva** [comment]
@ScottIsAFool A thousand apologies. As always used Windows Live Writer, which did not have as Blogger service option, I clicked Other. I could log in without problems.

**Comment by 1093brown** [comment]
Exactly the same here
Bob

**Comment by 1093brown** [comment]
Exactly the same as crpaiva
Bob

**Comment by crpaiva** [comment]
I have to thank a lot to the work of you.I was feeling abandoned. rsssss
I noticed that the feature "split post" is inhibited and access to YouTube account is returning error.

**Comment by willduff** [comment]
@SteveP-UK, what browser did the page launch in? I expect the page to navigate to that URL (that is how it sends the authentication token from the web browser to Open Live Writer), but it should have displayed a message that said "Please close this page." I use Microsoft Edge as my default browser and the tab automatically closes for me. Did you see different behavior than what I've described?

@crpaiva Thanks for pointing those out - I didn't see any support in the Blogger API v3 for split posts, so I'm not sure if we'll be able to add support for that again. I will reach out to Google about that.
I haven't changed any of the YouTube code yet, so I expect that to still be broken. I'll make sure it goes into the known issues list.

@1093brown, @farsideoffifty

**Comment by kathweaver** [comment]
Quick test of the "nightly" build.

Was able to login and make a quick post to Blogger.  

So far nothing appears to be broken and a lot is fixed.  Full test a bit later.

GOOD WORK!

**Comment by jdubyaeber** [comment]
OK Will Duff.



Just downloaded your build.



5.14mb of OLW goodness!



I am tsoorad.blogspot.com.  Windows 10 Ent on a Lenovo laptop.  Install went cleanly first try.  Opening on subsequent tries were successful.  I only have one blog, and the installer merely asked me to login to Google and it got a verification code and away I went.



http://tsoorad.blogspot.com/2015/12/test-post.html to see output of initial test blog.

YES YES YES!



Let me know when the next build is out and I will test again.



-John

________________________________

**Comment by SteveP-UK** [comment]
Will, I'm using Firefox v42. The only instruction on the page was to reload
the page, but that gave the same result. Hope this helpful.

Regards

Steve
www.StevePalmer.com
blog.StevePalmer.com

**Comment by comstech23** [comment]
Yes!! Thank you so much!! It worked :) The Split Post feature isn't working, but it's an easy fix to add:

 

at the point where you want to split the post. I just tested it out and it worked :) 

Y'all are amazing! Thank you!!

**Comment by NickyvVr** [comment]
Will,
I was able to add my blog at www.nickyvv.com and post a draft post. Great work so far!

You are saying *it should have displayed a message that said "Please close this page." [...] Did you see different behavior than what I've described?* 
I indeed saw the page with the message, but it didn't close itself afterwards. I was using Chrome (Version 47.0.2526.80 m (64-bit)).

Thanks,
Nicky

**Comment by quadrathon** [comment]
I am see some folks are able to log in, still not working for me. I am getting the User name error
![12-16-2015 3-32-11 pm](https://cloud.githubusercontent.com/assets/16316032/11854563/43a06aa8-a40a-11e5-86f8-d71363e43abf.jpg)

**Comment by NickyvVr** [comment]
@quadrathon Are you sure you downloaded the latest build from https://olw.blob.core.windows.net/nightly/Releases/OpenLiveWriterSetup.exe? Because you shouldn't be using a username and password anymore. It should go to Google for authorisation after clicking the sign in button instead.
![image](https://cloud.githubusercontent.com/assets/16239272/11854947/64587f82-a447-11e5-8e98-9c83e1ad07b8.png)

**Comment by wcjyao** [comment]
Was able to successfully log in! However upon downloading my current blogger theme, I'm only able to add text to the blog title and nowhere else. It it a problem with my theme? Screenshot attached
![no theme showing](https://cloud.githubusercontent.com/assets/16327839/11854998/59678be0-a3fc-11e5-9067-0c0eb186779e.jpg)

**Comment by ScottIsAFool** [comment]
@wcjyao if you click on Blog Account then blog theme, that should turn it off, are you able to then get into the post details?

**Comment by kathweaver** [comment]
I've been able to do several posts with both Blogger and Typepad.  Nothing appears to be broken by the fix <VBG> and I am able to post on both platforms.  Good job!

**Comment by ALCvA** [comment]
Many many thanks for your good news. I connected to Blogger with no problem. I do have two questions:

1. A spell-checker is essential. Will this be addressed or is another solution possible?
2. Starting OpenLiveWriter is unusual. How is this supposed to work?

**Comment by ScottIsAFool** [comment]
@ALCvA 1. Yes, spell checking is being tracked with #130 
2. Could you explain this a little more, please? What do you mean "unusual"? What are you seeing?

**Comment by 1093brown** [comment]
Will
Apologies I also didn't look and see Blogger on the initial set up screen
as with Live Writer you had to click 'other'
Reloaded OLW, clicked on blocker, went through verification process & then
I'm back in , well done, FANTASTIC :)
Will try to upload some posts later this evening.
Going in the right direction - THANK YOU for all the work you're doing to
bring this programme alive again
Bob

**Comment by ALCvA** [comment]
Dear Scott,

I start OpenLiveWriter by clicking on the OpenLiveWriterSetup icon—that 
is unusual? Or is there another way?

Dr Alfred L.C. van Amelsvoort
Hello! Contact me here <http://www.alcvanamelsvoort.com/contact-me>

**Comment by 1093brown** [comment]
Blogger not blocker !!

**Comment by willduff** [comment]
@ALCvA, the OpenLiveWriterSetup.exe is just the installer - except we made our installer so seamless, all it does is copy a folder and launch the app :). If you keep clicking on it, you will install over and over again. Instead, you should now have an Open Live Writer icon on your Desktop and in your Start Menu. Once you have Open Live Writer open, can right-click on the Open Live Writer icon in the task bar and choose 'Pin to taskbar' to make it easy to launch again.

**Comment by ScottIsAFool** [comment]
What @willduff said :)

**Comment by ALCvA** [comment]
Dear willduff and ScottIsAFool. Thanks for your good advise. The Open Live Writer icon is now securely pinned to the task bar.

**Comment by shanselman** [comment]
Ok, now that @willduff has promoted the first Blogger-supported build, let's NOT have folks using the Nightlies now. Use the release (and stay on it) at http://openlivewriter.org.

**Comment by markgossa** [comment]
This works great. Thanks a lot for doing this. I'm now posting away as normal. I've posted this article with no issues at all: http://markgossa.blogspot.com/2015/12/exchange-2013-to-2016-migration-part-5.html.

**Comment by The-Andy** [comment]
Worked fine for me too... http://www.seizingthedream.com/
Will this thread stay open until the labels/categories are working, or will there be a new item that we need to follow for that one?

**Comment by sheng-wang-i** [comment]
Tried out. It works!  I can now login and post (with images) again. 

hooray

**Comment by Xepetas** [comment]
It works for me with Blogger. LABELS cannot be found.

**Comment by quadrathon** [comment]
@NickyvVr thanks for the headsup I was using the previous days build! Looks great but is missing Labels

**Comment by wcjyao** [comment]
The timing of this couldn't have been better! Did my first post today with an all new layout + OLW: http://blog.simplytwo.com/2015/12/a-day-in-south-bay-with-amy-john.html

Thanks for all the hours you guys have put into this, f'realz

**Comment by farsideoffifty** [comment]
I just tried to publish a blog post The error says Can't publish files The remote server returned an error (403) forbidden.
Now what??

**Comment by JoniWebb** [comment]
omg!  thank you!  ok - reloaded the new OLW and got through the first screen, but then got this - should I removed the older OLW first and then add the new one again?  

![screenshot 2410](https://cloud.githubusercontent.com/assets/16286301/11861845/d19cf684-a449-11e5-887e-634b02e7494b.png)

**Comment by JoniWebb** [comment]
omg!!!!!  never mind!!  IT WORKS!!!!!!!!!!!!!!!!!!!  I just turned off the computer and tried again (duh!) omg!!!!!!!!!!!!!!!!!!!!!!!! thank you thank you thank you !!!!!  I love you!!!!!!!!!!   I've been worrying about Live Writer for years - and now!  no worries!  Thank you!!!!!!!!!!!!!!!!!

**Comment by ScottIsAFool** [comment]
@farsideoffifty To confirm, this was after you had successfully re-added your blog back into OLW using the new fix?

**Comment by ScottIsAFool** [comment]
Not sure, but this might be what @farsideoffifty is experiencing http://www.madrasnow.com/2015/12/solved-open-live-writer-login-issue.html we may need to put a fix in for this if it's a problem.

**Comment by crpaiva** [comment]
How happy I am !! Only you could have done such work.
Access to service video still returning error.
Split post is inhibited and unavailable categories.
Thanks again and again
![image](https://cloud.githubusercontent.com/assets/16322079/11869194/c8ad6530-a4a4-11e5-887a-f7e77360cf77.png)
![image](https://cloud.githubusercontent.com/assets/16322079/11869204/ebe22428-a4a4-11e5-80cc-3e11d1b2cb07.png)

**Comment by mswcap** [comment]
Awesome! I can connect now to my Blogger account. A job well done. Some other features are missing but I know they're in the pipeline. Thanks a lot for your hard work!

**Comment by jes2015** [comment]
Had a couple of false starts - it ran only on the third attempt but then executed OK. I did notice that there is no Set Categories bar at the top below the menu, something I used on my posts. My post went up smoothly, text, video and photo all intact.

**Comment by ericasisme** [comment]
OH NO!  I tried again, this morning, and IT DOES NOT WORK!

Steps to reproduce:
1. Delete blog post (b/c I had wanted to re-upload with a pic sized
differently)
2. Click publish to re-upload.
3.  Get error message:  The remote server returned an error: (403)
Forbidden.
4.  Try to close and re-open and try again
5.  Get error message:  The remote server returned an error: (403)
Forbidden.

**Comment by ScottIsAFool** [comment]
@ericasisme Can you try the instructions from this blog post? http://www.madrasnow.com/2015/12/solved-open-live-writer-login-issue.html

**Comment by Stardate244** [comment]
I downloaded the newest build but I am unable to run it. Nothing happens at all, the mouse pointer turns into the blue circle (Windows 10) as just goes round and round. I have tried 4 times now but nothing. Anyone else had this problem or any ideas?

**Comment by ericasisme** [comment]
Hi Scott, sorry, I've left my home and 2nd career for the day for my 1st
career.  I can try tonight.

**Comment by ericasisme** [comment]
I did read the fix though.  Will it always be an open bug with a
workaround, or will a subsequent release store the password upon set-up?

(My 1st career happens to be QA Engineering and Project Management for a
software development company) ;)

**Comment by ScottIsAFool** [comment]
@ericasisme we'll definitely be making sure there is a fix in place if we can get one.

**Comment by StephenCWLL** [comment]
@Stardate244 Wonder if that's SmartScreen stopping it. Should flag up a warning though. Tried restarting PC, just in case something odd has gone wrong in background?

**Comment by Stardate244** [comment]
@ericasisme I've switched off Smartscreen even though I use Firefox, just to be sure. Still no joy. I've restarted the laptop after every try. The original build ran but I got the invalid username/password error but this build won't run at all.

**Comment by ScottIsAFool** [comment]
@Stardate244 do you have a shortcut for it on your desktop?

**Comment by farsideoffifty** [comment]
Scott, The work around worked for me with the Forbidden 403.  I had to add my google password to each blog account like you said.  Thank you!  I tried one dummy post and it seemed to work, keeping my fingers crossed.

**Comment by Dinchy87** [comment]
Tested the new release today and posting to draft works so far and picture upload too. The formating is the same like wlw. The only thing now missing for me is categories. Oh and is there in plan to have an update mechanism inside the app so it notifies us for new releases and/or updates itself ?! so we dont have to redeownload each time because some of us dont track the github always and for them it would be good to Know. And maybe a "whats new window" that shows the changelog? but so far great work on making this happen!

**Comment by ScottIsAFool** [comment]
@Dinchy87 it will auto-update itself. If you have Writer open and there's an update it gets downloaded, next time you launch Writer, you'll have that updated version. There's nothing you need to manually do.

**Comment by StephenCWLL** [comment]
@ScottIsAFool Seriosuly dislike auto-updates. It's like Windows 10 behaviour in software too :) By nice to have the option for it to check and alert us so we can initiate the update too.

**Comment by Dinchy87** [comment]
Oh nice :) i redownloaded the new version asi  tought it has not updated itself in the back. :) still a confirmation would be nice and a whats new window maybe.

**Comment by ScottIsAFool** [comment]
Raise it as an issue so we can track that.

**Comment by Stardate244** [comment]
@ScottIsAFool Nothing at all. I'm trying to run it again now, but without success.

**Comment by StephenCWLL** [comment]
@Stardate244 I assume any other exe runs? You've not turned off UAC have you? That can stop things in some circumstances.

**Comment by anserq** [comment]
I am getting the forbidden error as well.
Can't publish files
The remote server returned an error: (403) Forbidden.

**Comment by StephenCWLL** [comment]
@anserq Do what this says to fix that :) http://www.madrasnow.com/2015/12/solved-open-live-writer-login-issue.html

**Comment by anserq** [comment]
Okay thanks @StephenCWLL

**Comment by willduff** [comment]
@Stardate244 Can you please email your `%localappdata%\SquirrelTemp\SquirrelSetup.log` file to openlivewriter-team@dotnetfoundation.org? Or let me know if you don't have this file. Thanks.

**Comment by madm110** [comment]
@StephenCWLL I just tried that fix and unfortunately it won't let me type anything in the password box? Am I doing something wrong?

**Comment by madm110** [comment]
OK... I deleted the blog and then added it again for it to pick up the password and it's working again. It seems as though when you turn off your computer it loses the password.

Also wanted to say a huge thanks to you guys for all your hard work. This is an invaluable tool for our blog and we would be lost without it. THANK YOU <3

**Comment by farsideoffifty** [comment]
Tonight I got Forbidden error (403) on two of my blogs.  I  had to update my account configuration with every blog I write.  It is not keeping the password for some reason.  Seems like a strange glitch.

**Comment by Virtual-Nihilist-Blog** [comment]
The original topic of this issue was that we could not connect to Blogger using OLW.  This has been fixed and we are now able to connect to our Blogger sites, but the discussion has now turned to new issues we are now seeing.  I would like to suggest that this issue be closed as fixed and people open new issues for the other problems they are experiencing.  This thread has been suffering from way too much drift and it will make it difficult for everyone to follow, including the team of developers who have been diligently working to address our problems in a timely fashion.  Thank you to the OLW team for a very professional job on this project.

**Comment by Stardate244** [comment]
@willduff @StephenCWLL . It's working. I don't think the previous build had uninstalled properly, so I went through the registry and deleted any reference to OLW. Re-booted and the software installed perfectly. Test post done, with text and photo and there were no problems. Thank you for all your help. So happy to be using this software.

**Comment by anserq** [comment]
Hello, I still get the forbidden error.
Can't publish files
The remote server returned an error: (403) Forbidden.

**Comment by beingyogiraj** [comment]
[Fix “The Remote Server Returned An Error: (403) Forbidden” Issue In Olw](http://www.thegeekydude.com/2015/12/fix-remote-server-returned-error-403.html)

**Comment by anserq** [comment]
The password is saved. I already entered the  password and saved it.
It's still giving the error.

**Comment by farsideoffifty** [comment]
I am still getting the Forbidden 403 error also,  I have to update my account configuration every time I post to blogger.  I have saved my password too, many times.  Is anyone working on this error? I have four blogs each with a different template.

**Comment by farsideoffifty** [comment]
beingyogiraj that fix does not work for everyone.

**Comment by willduff** [comment]
The workaround is slightly incorrect - Writer does not ever send your password to Blogger, so it doesn't matter what you type into the field. However, just the act of clicking through to change your password will authenticate you with Blogger for 24 hours. So you can just try the workaround again and type in a random password. I'm going to put in a real fix for the Forbidden 403 error soon - stay tuned!

**Comment by anserq** [comment]
Thanks @willduff

**Comment by farsideoffifty** [comment]
Thanks wilduff

**Comment by Shoshiplatypus** [comment]
I have been eagerly following all the comments and developments of the new Open LiveWriter and thought that enough work had now been done for me to test it out for myself, and after disabling the two-step log-in process on Google (which I hated anyway!) I have just published my first post, on my second blog (http://thegutlessbaglady.com). Result: COMPLETE SUCCESS!!! I am delighted. It is some time since I have been able to publish anything on either blog, and I am so, so grateful to all of the hardworking team who have been labouring on our behalf to make blogging a happy experience once more. Thank you very, very much. (I use Windows 10.)

Eagerly awaiting the ability to add categories now, but in the meantime, as long as it is up and running and I have no further log-in problems, I am more than satisfied.

Again, grateful thanks!

Shoshi

**Comment by anserq** [comment]
Hello.
I am using the 0.5.1.2  version of open live writer. Last night, i was having issues publishing the post.Is there 403 forbidden error fixed? What should I do to get up and running with the latest version?

**Comment by ScottIsAFool** [comment]
@anserq Open up Live Writer, leave it a minute, then restart it, that should have updated you. To check, click on File > About Open Live Writer, you want to be on 0.5.1.3

**Comment by anserq** [comment]
Okay i'm updated to the new version. Thanks!

**Comment by lextm** [comment]
@Shoshiplatypus why do you disable two factor authentication? You should be able to generate an application specific password for Luve Writer instead, and use two factor for others.

**Comment by Shoshiplatypus** [comment]
Someone on here: http://answers.microsoft.com/en-us/windowslive/forum/writer-program/windows-live-writer-wont-connect-to-blogger/f3ae8ae5-f013-477b-b262-399430d29e28?page=15&msgId=2e74212d-05a3-453c-93b8-36f4016b79b4&auth=1 suggested turning off 2-step authentication and it worked for them, so that's what I did too.

I have a problem in that I cannot upload videos onto my blog in OLW - I choose the option to upload from my hard drive and I get a menu that wants me to log in to Youtube. Youtube isn't accepting my username/password so I can't add videos direct from Youtube either.

**Comment by ScottIsAFool** [comment]
The youtube issue is a known issue (#16) we hope to address it soon.

**Comment by 1093brown** [comment]
@WillDuff - Tried to open previously published post (recent post) and got
the following error.
Logged out & back in, updated account. Still the same error.
Thanks
Bob

**Comment by Shoshiplatypus** [comment]
Thank you ScottIsAFool - that's good to know! So far, though, everything is looking great, and it is SO GOOD to be back in Blogland again.

Is work also being done to enable us to add categories? That would be great. Thanks again for all your hard work.

Shoshi

**Comment by martinwoodward** [comment]
Thanks everyone. I think we think we have fixed this mostly now in 0.5.1.3 bar the known issues and this thread is getting a little long - for any additional Blogger issues be worth raising as a new issue once you have tried the following:

 - Download and install the latest build from http://openlivewriter.org
 - Go to File, About Open Live Writer to confirm you are running version 0.5.1.3 or higher
 - Delete your old blog account from Manage Accounts
 - Add your blogger account back. You should be prompted to authenticate using a pop-up web form rather than the old username/password form

Thanks for all the help!

**Comment by undercovergypsy** [comment]
Okay this is 2020 and what about this? I am so disappointed that this doesn't work again.
![Annotation 2020-02-23 075835](https://user-images.githubusercontent.com/60517809/75117081-8e003600-5612-11ea-94e4-45827d5e956a.png)
